# Generated by Django 3.0.3 on 2020-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_cofirmed', models.BooleanField(blank=True, default=False, verbose_name='Выполнена')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Пользователь')),
                ('password', models.CharField(default='', max_length=16, verbose_name='Пароль')),
            ],
        ),
    ]
