# Generated by Django 3.0.3 on 2020-03-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20200305_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('is_cofirmed', 'on_main', 'title', 'user', 'email', 'pub_date')},
        ),
        migrations.AddField(
            model_name='task',
            name='on_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='Показывать на главной'),
        ),
    ]
