# Generated by Django 3.0.3 on 2020-03-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.CharField(default='', max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default='', max_length=200, verbose_name='Пользователь'),
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('is_cofirmed', 'title', 'user', 'email', 'pub_date')},
        ),
    ]
